In [7]:
import pandas as pd

In [8]:
# read csv
df = pd.read_csv("atp_tennis.csv", low_memory=False)

In [9]:
df.dtypes

Tournament        str
Date              str
Series            str
Court             str
Surface           str
Round             str
Best of         int64
Player_1          str
Player_2          str
Winner            str
Rank_1          int64
Rank_2          int64
Pts_1           int64
Pts_2           int64
Odd_1         float64
Odd_2             str
Score             str
dtype: object

In [10]:
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1,6-4 6-2
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1,3-6 3-6
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,40,655,-1,-1,-1.0,-1,6-7 7-5 6-3
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,87,65,-1,-1,-1.0,-1,1-6 4-6
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,Fromberg R.,81,198,-1,-1,-1.0,-1,7-6 5-7 6-4

In [11]:
dtype = {
    "tournament": "string",
    "date": "string",
    "series": "string",
    "court": "string",
    "surface": "string",
    "round": "string",
    "BestOf": "Int64",
    "player1": "string",
    "player2": "string",
    "winner": "string",
    "rank1": "Int64",
    "rank2": "Int64",
    "pts1": "Int64",
    "pts2": "Int64",
    "odds1": "Float64",
    "odds2": "Float64",
    "score": "string"
}

parse_dates = [
    "Date"
    ]

In [12]:
df['Date'] = pd.to_datetime(df['Date'])
df['Odd_1'] = pd.to_numeric(df['Odd_1'], errors='coerce')
df['Odd_2'] = pd.to_numeric(df['Odd_2'], errors='coerce')

In [13]:
# clean df
df = df[(df['Date'] >= '2010-01-01') & (df['Odd_1'] > 0) & (df['Odd_2'] > 0)].copy()
df = df.sort_values('Date').reset_index(drop=True)

In [14]:
df['target'] = (df['Player_1'] == df['Winner']).astype(int)

In [15]:
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,target
0,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Nieminen J.,Gasquet R.,Gasquet R.,88,52,568,850,2.62,1.44,3-6 6-4 4-6,0
1,Chennai Open,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Giraldo S.,Phau B.,Giraldo S.,107,111,516,496,2.00,1.72,6-4 6-7 6-3,1
2,Chennai Open,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Greul S.,Hajek J.,Hajek J.,59,103,739,526,1.44,2.62,6-3 2-6 4-6,0
3,Chennai Open,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Cilic M.,Kunitsyn I.,Cilic M.,14,104,2430,525,1.12,5.50,6-2 6-4,1
4,Qatar Exxon Mobil Open,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Gimeno-Traver D.,Troicki V.,Troicki V.,72,29,613,1175,4.50,1.16,1-6 5-7,0

In [16]:
df.count()

Tournament    39630
Date          39630
Series        39630
Court         39630
Surface       39630
Round         39630
Best of       39630
Player_1      39630
Player_2      39630
Winner        39630
Rank_1        39630
Rank_2        39630
Pts_1         39630
Pts_2         39630
Odd_1         39630
Odd_2         39630
Score         39630
target        39630
dtype: int64

In [17]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/my_taxi')

In [18]:
print(pd.io.sql.get_schema(df, name='tenis_data', con=engine))

CREATE TABLE tenis_data (
	"Tournament" TEXT,
	"Date" TIMESTAMP WITHOUT TIME ZONE,
	"Series" TEXT,
	"Court" TEXT,
	"Surface" TEXT,
	"Round" TEXT,
	"Best of" BIGINT,
	"Player_1" TEXT,
	"Player_2" TEXT,
	"Winner" TEXT,
	"Rank_1" BIGINT,
	"Rank_2" BIGINT,
	"Pts_1" BIGINT,
	"Pts_2" BIGINT,
	"Odd_1" FLOAT(53),
	"Odd_2" FLOAT(53),
	"Score" TEXT,
	target BIGINT
)

In [19]:
df.head(n=0).to_sql(name='tenis_data', con=engine, if_exists='replace')

0

In [79]:
import pandas as pd

df_iter = pd.read_csv(
    'atp_tennis.csv',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=5000
)
all_chunks = []

for chunk in df_iter:
    chunk['Odd_1'] = pd.to_numeric(chunk['Odd_1'], errors='coerce')
    chunk['Odd_2'] = pd.to_numeric(chunk['Odd_2'], errors='coerce')
    
    
    df_chunk['Date'] = pd.to_datetime(df_chunk['Date'], errors='coerce')

    chunk = chunk[
        (chunk['Date'] >= '2015-01-01') & 
        (chunk['Odd_1'] > 0) & 
        (chunk['Odd_2'] > 0)
    ].copy()

    chunk['target'] = (chunk['Player_1'] == chunk['Winner']).astype(int)
    
    all_chunks.append(chunk)
    print('listo')

df_final = pd.concat(all_chunks).sort_values('Date').reset_index(drop=True)

listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo

In [90]:
print("--- Validación de Límites ---")
print(f"Fecha mínima encontrada: {df_final['Date'].max()}")
print(f"Cuota mínima Odd_1: {df_final['Odd_1'].min()}")
print(f"Cuota mínima Odd_2: {df_final['Odd_2'].min()}")

--- Validación de Límites ---
Fecha mínima encontrada: 2026-03-01 00:00:00
Cuota mínima Odd_1: 0.967
Cuota mínima Odd_2: 0.967

In [87]:
print(df_final.count())

Tournament    27030
Date          27030
Series        27030
Court         27030
Surface       27030
Round         27030
Best of       27030
Player_1      27030
Player_2      27030
Winner        27030
Rank_1        27030
Rank_2        27030
Pts_1         27030
Pts_2         27030
Odd_1         27030
Odd_2         27030
Score         27030
target        27030
dtype: int64

In [89]:
# Definimos el nombre de la tabla
table_name = 'tenis_data'

# Subida directa
df_final.to_sql(
    name=table_name,
    con=engine,
    if_exists='replace', # 'replace' crea la tabla de nuevo; 'append' añade datos
    index=False,         # No guardamos el índice de pandas como columna
    method='multi',      # CRITICO: Agrupa filas para insertar más rápido
    chunksize=5000       # Pandas divide el DF en pedazos al enviarlo a SQL
)

print(f"¡Éxito! Se han subido {len(df_final)} filas a la tabla '{table_name}'.")

¡Éxito! Se han subido 27030 filas a la tabla 'tenis_data'.

In [13]:
import pandas as pd
from sqlalchemy import create_engine

dtype = {
    "tournament": "string",
    "date": "string",
    "series": "string",
    "court": "string",
    "surface": "string",
    "round": "string",
    "BestOf": "Int64",
    "player1": "string",
    "player2": "string",
    "winner": "string",
    "rank1": "Int64",
    "rank2": "Int64",
    "pts1": "Int64",
    "pts2": "Int64",
    "odds1": "Float64",
    "odds2": "Float64",
    "score": "string"
}

parse_dates = [
    "Date"
]

filename = 'atp_tennis.csv'
tableName = 'tenis_data'
chunksize = 5000
pg_user = 'root'
pg_pass = 'root'
pg_host = 'localhost'
pg_port = 5432
pg_db = 'my_taxi'

engine = create_engine(f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}')


df_iter = pd.read_csv(
    filename,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=chunksize
)
all_chunks = []

for chunk in df_iter:
    chunk['Odd_1'] = pd.to_numeric(chunk['Odd_1'], errors='coerce')
    chunk['Odd_2'] = pd.to_numeric(chunk['Odd_2'], errors='coerce')


    chunk['Date'] = pd.to_datetime(chunk['Date'], errors='coerce')

    chunk = chunk[
        (chunk['Date'] >= '2015-01-01') & 
        (chunk['Odd_1'] > 0) & 
        (chunk['Odd_2'] > 0)
    ].copy()

    chunk['target'] = (chunk['Player_1'] == chunk['Winner']).astype(int)

    all_chunks.append(chunk)
    print('listo')

df_final = pd.concat(all_chunks).sort_values('Date').reset_index(drop=True)


print("--- Validación de Límites ---")
print(f"Fecha mínima encontrada: {df_final['Date'].max()}")
print(f"Cuota mínima Odd_1: {df_final['Odd_1'].min()}")
print(f"Cuota mínima Odd_2: {df_final['Odd_2'].min()}")

# Subida directa
df_final.to_sql(
    name=table_name,
    con=engine,
    if_exists='replace', # 'replace' crea la tabla de nuevo; 'append' añade datos
    index=False,         # No guardamos el índice de pandas como columna
    method='multi',      # CRITICO: Agrupa filas para insertar más rápido
    chunksize=chunksize     # Pandas divide el DF en pedazos al enviarlo a SQL
)

print(f"¡Éxito! Se han subido {len(df_final)} filas a la tabla '{tableName}'.")

listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
listo
--- Validación de Límites ---
Fecha mínima encontrada: 2026-03-01 00:00:00
Cuota mínima Odd_1: 0.967
Cuota mínima Odd_2: 0.967
¡Éxito! Se han subido 27030 filas a la tabla 'tenis_data'.